title: testing1
description: Central hub for community resources at UH.
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: true
  repository_url: https://github.com/testing-this-a/testing-this-a
  document_url: https://github.com/testing-this-a/test1
gems:
  - jekyll-mentions
